name: Version Tagger

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  tag-if-needed:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须有写权限才能推送标签

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get package.json version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if tag exists and create if not
        # 将两个 token 都传递给步骤的环境变量
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG_NAME="v$VERSION"

          echo "Checking for tag: $TAG_NAME"

          if git tag -l "$TAG_NAME" | grep -q "$TAG_NAME"; then
            echo "Tag $TAG_NAME already exists. No action needed."
          else
            echo "Tag $TAG_NAME does not exist. Creating and pushing tag..."
          
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "$TAG_NAME"
          
            # 核心逻辑：检查 ACTIONS_PAT 是否存在且不为空
            if [ -n "$ACTIONS_PAT" ]; then
              echo "ACTIONS_PAT found. Pushing with PAT to trigger subsequent workflows..."
              # 使用 PAT 推送，这可以触发其他工作流
              # 注意：${{ github.repository }} 是一个动态变量，例如 "owner/repo-name"
              git push https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}.git "$TAG_NAME"
            else
              echo "ACTIONS_PAT not found. Pushing with GITHUB_TOKEN (will not trigger subsequent workflows)..."
              # 回退到使用 GITHUB_TOKEN 推送
              git push origin "$TAG_NAME"
            fi
          
            echo "Successfully created and pushed tag $TAG_NAME."
          fi